"""
Test Cases for Banking Fraud Investigation
Contains 3 case types: Normal, Ambiguous/Exception, and High-Risk
"""

import datetime

TEST_CASES = {
    "CASE-2024-001": {
        "case_id": "CASE-2024-001",
        "case_type": "Normal",
        "alert_type": "Unusual Transaction Pattern",
        "severity": "Medium",
        "timestamp": "2024-10-04 09:23:14",
        "customer": {
            "id": "CUST-88234",
            "name": "Rajesh Mehta",
            "age": 42,
            "account_type": "Savings",
            "account_age_years": 8,
            "kyc_status": "Verified",
            "risk_profile": "Low",
            "average_monthly_balance": 245000,
            "occupation": "Software Engineer",
            "city": "Pune",
            "phone_verified": True,
            "email_verified": True,
        },
        "transaction": {
            "txn_id": "TXN-9928374",
            "amount": 48000,
            "currency": "INR",
            "type": "UPI Transfer",
            "channel": "Mobile App",
            "merchant": "N/A - P2P Transfer",
            "recipient": "Suresh Mehta (Brother)",
            "location": "Pune, Maharashtra",
            "device_id": "DEV-MOB-4421",
            "ip_address": "103.21.58.xx",
            "device_fingerprint_match": True,
            "time_of_day": "09:23 AM",
            "is_first_time_recipient": False,
        },
        "historical_context": {
            "similar_txns_last_6mo": 12,
            "avg_txn_amount": 35000,
            "max_txn_amount": 75000,
            "failed_login_attempts_24h": 0,
            "password_changed_recently": False,
            "device_change_recent": False,
            "previous_fraud_cases": 0,
        },
        "rule_triggers": [
            {"rule_id": "R-101", "rule_name": "Amount > 2x avg daily", "severity": "Low"},
        ],
        "expected_outcome": "Approve - Legitimate family transfer, consistent behaviour",
    },

    "CASE-2024-002": {
        "case_id": "CASE-2024-002",
        "case_type": "Ambiguous / Exception",
        "alert_type": "Velocity Rule Breach + New Device",
        "severity": "High",
        "timestamp": "2024-10-04 02:47:33",
        "customer": {
            "id": "CUST-55102",
            "name": "Priya Sharma",
            "age": 29,
            "account_type": "Current",
            "account_age_years": 3,
            "kyc_status": "Verified",
            "risk_profile": "Medium",
            "average_monthly_balance": 182000,
            "occupation": "Freelance Designer",
            "city": "Mumbai",
            "phone_verified": True,
            "email_verified": True,
        },
        "transaction": {
            "txn_id": "TXN-3384756",
            "amount": 95000,
            "currency": "INR",
            "type": "NEFT Transfer",
            "channel": "Internet Banking",
            "merchant": "N/A - P2P Transfer",
            "recipient": "Ankit Verma (Unregistered Beneficiary)",
            "location": "Delhi, NCR",
            "device_id": "DEV-WEB-NEW-8812",
            "ip_address": "49.36.12.xx",
            "device_fingerprint_match": False,
            "time_of_day": "02:47 AM",
            "is_first_time_recipient": True,
        },
        "historical_context": {
            "similar_txns_last_6mo": 2,
            "avg_txn_amount": 25000,
            "max_txn_amount": 60000,
            "failed_login_attempts_24h": 2,
            "password_changed_recently": False,
            "device_change_recent": True,
            "previous_fraud_cases": 0,
        },
        "rule_triggers": [
            {"rule_id": "R-201", "rule_name": "New device + high-value txn", "severity": "High"},
            {"rule_id": "R-205", "rule_name": "Transaction outside normal hours", "severity": "Medium"},
            {"rule_id": "R-210", "rule_name": "Amount > 3x avg + new beneficiary", "severity": "High"},
            {"rule_id": "R-215", "rule_name": "Geo-location mismatch (Mumbai->Delhi)", "severity": "Medium"},
        ],
        "expected_outcome": "Hold & Verify - Multiple suspicious signals but could be legitimate travel/freelance payment",
    },

    "CASE-2024-003": {
        "case_id": "CASE-2024-003",
        "case_type": "High-Risk",
        "alert_type": "Account Takeover Suspected",
        "severity": "Critical",
        "timestamp": "2024-10-04 04:12:08",
        "customer": {
            "id": "CUST-12890",
            "name": "Vikram Desai",
            "age": 67,
            "account_type": "Savings",
            "account_age_years": 22,
            "kyc_status": "Verified",
            "risk_profile": "Low",
            "average_monthly_balance": 1850000,
            "occupation": "Retired Government Officer",
            "city": "Bengaluru",
            "phone_verified": True,
            "email_verified": True,
        },
        "transaction": {
            "txn_id": "TXN-7712093",
            "amount": 490000,
            "currency": "INR",
            "type": "RTGS Transfer",
            "channel": "Internet Banking",
            "merchant": "N/A - P2P Transfer",
            "recipient": "Crypto Exchange Wallet (Unregistered Beneficiary)",
            "location": "Lagos, Nigeria (VPN Detected)",
            "device_id": "DEV-WEB-UNKNOWN-0091",
            "ip_address": "196.46.33.xx",
            "device_fingerprint_match": False,
            "time_of_day": "04:12 AM",
            "is_first_time_recipient": True,
        },
        "historical_context": {
            "similar_txns_last_6mo": 0,
            "avg_txn_amount": 15000,
            "max_txn_amount": 50000,
            "failed_login_attempts_24h": 7,
            "password_changed_recently": True,
            "device_change_recent": True,
            "previous_fraud_cases": 0,
        },
        "rule_triggers": [
            {"rule_id": "R-301", "rule_name": "Foreign IP + VPN detected", "severity": "Critical"},
            {"rule_id": "R-302", "rule_name": "Multiple failed logins -> password change -> high txn", "severity": "Critical"},
            {"rule_id": "R-303", "rule_name": "Amount > 10x avg + crypto destination", "severity": "Critical"},
            {"rule_id": "R-304", "rule_name": "Unknown device + elderly customer", "severity": "High"},
            {"rule_id": "R-305", "rule_name": "Transaction at unusual hour for customer profile", "severity": "High"},
            {"rule_id": "R-306", "rule_name": "Beneficiary pattern: crypto exchange (high risk category)", "severity": "Critical"},
        ],
        "expected_outcome": "Block & Escalate - Strong indicators of account takeover targeting elderly customer",
    },
}
